name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libjack-jackd2-dev liblo-dev libsdl2-dev libsdl2-ttf-dev librtmidi-dev libsndfile1-dev libflac-dev patchelf libfuse-dev cmake

      - name: Build project
        run: make

      - name: Create release
        run: ./build-appimage.sh

      - name: Create release artifact
        run: |
          cp ooooooo.AppImage ooooooo_${{ github.event.release.name }}.AppImage
          ls -lSh ooooooo_${{ github.event.release.name }}.AppImage

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install dependencies
        run: |
          brew update
          brew install jack liblo sdl2 sdl2_ttf rtmidi libsndfile flac create-dmg fuse cmake

      - name: Set PKG_CONFIG_PATH
        run: echo "PKG_CONFIG_PATH=/opt/homebrew/lib/pkgconfig" >> $GITHUB_ENV

      - name: Build project
        run: |
          export PKG_CONFIG_PATH="/opt/homebrew/lib/pkgconfig:/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH"
          export CXXFLAGS="-I/opt/homebrew/include -I/usr/local/include"
          export LDFLAGS="-L/opt/homebrew/lib -L/usr/local/lib"
          export PATH="/opt/homebrew/bin:$PATH"
          make
      - name: Build macOS app
        run: |
          chmod +x build-macapp.sh
          ./build-macapp.sh
      - name: Create release artifact
        run: |
          ls -lSh
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-pkg-config
            mingw-w64-x86_64-python
            mingw-w64-x86_64-jack2
            mingw-w64-x86_64-liblo
            mingw-w64-x86_64-SDL2
            mingw-w64-x86_64-SDL2_ttf
            mingw-w64-x86_64-rtmidi
            mingw-w64-x86_64-libsndfile
            mingw-w64-x86_64-flac
            mingw-w64-x86_64-make
            mingw-w64-x86_64-cmake
            zip
      - name: Check MSYS2 environment
        shell: msys2 {0}
        run: |
          which gcc
          which g++
          echo $PATH
          cmake --version
          pkg-config --libs jack
          ls -la /mingw64/lib/*jack*
      - name: Build in MSYS2 environment
        shell: msys2 {0}
        run: |
          mkdir -p build
          cd build
          export PATH="/mingw64/bin:$PATH"
          export PKG_CONFIG_PATH="/mingw64/lib/pkgconfig:$PKG_CONFIG_PATH"
          export MINGW_PREFIX="/mingw64"
          cmake -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_PREFIX_PATH=/mingw64 \
                ..
          cmake --build . --config Release
      - name: Create release artifact
        shell: msys2 {0}
        run: |
          mkdir oooooooo
          cp build/clients/oooooooo/oooooooo.exe oooooooo/
          cp external/windows/*.dll oooooooo/
          zip -r oooooooo_${{ github.event.release.name }}.zip oooooooo
          ls -lSh oooooooo_${{ github.event.release.name }}.zip
